version: '3.7'

services:
  tails-server:
    image: ghcr.io/bcgov/tails-server:latest
    command: >
      tails-server
        --host 0.0.0.0
        --port 6543
        --storage-path=/tmp/tails-files  
        --log-level=INFO  
    environment:
      GENESIS_URL: "http://10.133.133.9:9000/genesis"
      STORAGE_PATH: "/tmp/tails-files"
      LOG_LEVEL: "INFO"
      TAILS_SERVER_URL: "http://10.133.133.10:6543"
    networks:
      sandbox:
        ipv4_address: 10.133.133.10
    ports:
      - "6543:6543"
    volumes:
      - "./tails-files:/tmp/tails-files"

networks:
  sandbox:
    external: true
    name: sandbox
